# Generated by Django 4.1.7 on 2023-04-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0004_alter_ebookmodel_cover_image_alter_ebookmodel_file_and_more"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price_to_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AddField(
            model_name="order",
            name="ebook",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ebook.ebookmodel",
            ),
        ),
        migrations.DeleteModel(
            name="OrderProduct",
        ),
    ]
