# Generated by Django 4.1.7 on 2023-04-01 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ebook", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ebookfavouritesmodel",
            name="favourite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ebooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebook.categorymodel",
            ),
        ),
    ]
