# Generated by Django 4.1.7 on 2023-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebookmodel",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ebookmodel",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=21, null=True
            ),
        ),
    ]
