# Generated by Django 4.1.7 on 2023-04-24 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0003_ebookmodel_is_free_ebookmodel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebookmodel",
            name="cover_image",
            field=models.ImageField(default=1, upload_to="images/ebook/Ebook/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ebookmodel",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="files/ebook/Ebook/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ebookmodel",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
