# Generated by Django 4.1.7 on 2023-04-07 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0003_ebookmodel_is_free_ebookmodel_price"),
        ("common", "0002_commentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="ebook",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebook.ebookmodel",
            ),
            preserve_default=False,
        ),
    ]
